---
- name: inatall dotnet
  hosts: all
  become: yes
  tasks:
    - name: wget the packages
      get_url: 
        url: "{{ packages_url }}"
        dest: /tmp/packages-microsoft-prod.deb
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: get url to /tmp/
      ansible.builtin.get_url:
        url: "{{ packages_url }}"
        dest: /tmp/
      when: ansible_facts['distribution'] == "CentOS"
    - name: install the packages-microsoft-prod.deb
      dpkg_selections:
        name: "{{ deb_packges }}"
        selection: install
      when: ansible_facts['distribution'] == "Ubuntu"