---
- name: inatall dotnet
  hosts: all
  become: yes
  vars:
    packages_url: https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
    dotnet_packages: 
      - dotnet-sdk-6.0
      - aspnetcore-runtime-6.0
      - dotnet-runtime-6.0
  tasks:
    - name: get url to /tmp/
      ansible.builtin.get_url:
        url: "{{ packages_url }}"
        dest: /tmp/
    - name: install dotnet-sdk-6.0, aspnetcore-runtime-6.0, dotnet-runtime-6.0
      yum: 
        name: "{{ dotnet_packages }}"
        state: present 