---
- name: Install Java-11
  hosts: all
  become: yes
  tasks: 
    - name: apt update
      apt:
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: java-11 install
      apt: 
        name: default-jre
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: java-11 install
      yum: 
        name: java-11-openjdk-devel
        state: present
      when: ansible_facts['distribution'] == "CentOS"