---
# tasks file for my
- name: get url to /tmp/
  ansible.builtin.get_url:
    url: "{{ packages_url }}"
    dest: "{{ packages_dest }}"
  when: ansible_facts['distribution'] == "CentOS"
- name: packages-microsoft-prod
  ansible.builtin.yum:
    name: "{{ packages_dest }}"
    state: present
  when: ansible_facts['distribution'] == "CentOS"
- name: install dotnet
  ansible.builtin.yum: 
    name: "{{ dotnet_packages }}"
    state: present