---
- name: Install Java-11
  hosts: all
  become: yes
  tasks: 
    - name: apt update
      apt:
        update_cache: yes
    - name: java-11 install
      apt: 
        name: default-jre
        state: present