---
- name: install nodejs on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install nodejs on ubuntu
      ansible.builtin.apt:
        name: 
          - nodejs
          - npm
        update_cache: yes
        state: present