---
- name: inatall dotnet
  hosts: all
  become: yes
  tasks:
    - name: get url to /tmp/
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
        dest: /tmp/
    - name: install dotnet-sdk-6.0, aspnetcore-runtime-6.0, dotnet-runtime-6.0
      yum: 
        name: 
          - dotnet-sdk-6.0
          - aspnetcore-runtime-6.0
          - dotnet-runtime-6.0
        state: present 