---
- name: inatall dotnet
  hosts: all
  become: yes
  tasks: 
    - name: wget the packages
      get_url: 
        url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dest: /tmp/
    - name: install the packages-microsoft-prod.deb
      dpkg_selections:
        name: packages-microsoft-prod.deb
        selection: install
    - name: rm in packages-microsoft-prod.deb
      file: 
        path: /tmp/packages-microsoft-prod.deb
        state: absent
    - name: install dotnet-sdk-7.0, aspnetcore-runtime-7.0, dotnet-runtime-7.0
      apt: 
        name: 
          - dotnet-sdk-6.0
          - aspnetcore-runtime-7.0
          - dotnet-runtime-7.0
        update_cache: yes
        state: present