---
- name: inatall dotnet
  hosts: all
  become: yes
  tasks: 
    - name: install dotnet-sdk-6.0, aspnetcore-runtime-6.0, dotnet-runtime-6.0
      apt: 
        name: 
          - dotnet-sdk-6.0
          - aspnetcore-runtime-6.0
          - dotnet-runtime-6.0
        update_cache: yes
        state: present