---
- name: install nodejs on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: Downloading nodejs setup file
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_18.x
        dest: /tmp/setup_18.x.sh
        mode: '0777'
    - name: Execute shell file
      ansible.builtin.shell: "/tmp/setup_18.x.sh"
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
    - name: Install nodejs
      ansible.builtin.apt: 
        name: nodejs
        state: present