---
all:
  children:
    nodejs_server:
      hosts:
        localhost:
          nodejs_package_version: 18
          nodejs_package_url: "https://deb.nodesource.com/setup_{{nodejs_package_version}}.x"
        172.31.24.105:
          nodejs_package_version: 10
          nodejs_package_url: "https://rpm.nodesource.com/setup_{{nodejs_package_version}}.x"
      vars:
        nodejs_package_dest: "/tmp/setup_{{nodejs_package_version}}.x.sh"
        nodejs_package: nodejs