---
- name: install nodejs on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Downloading nodejs setup file
      ansible.builtin.get_url:
        url: "{{nodejs_package_url}}"
        dest: "{{nodejs_package_dest}}"
        mode: '0777'
    - name: Execute shell file
      ansible.builtin.shell: "{{nodejs_package_dest}}"
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Install nodejs
      ansible.builtin.package: 
        name: "{{nodejs_package}}"
        state: present