---
- name: Install Java-11
  hosts: all
  become: yes
  tasks: 
    - name: apt update
      apt:
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: java-11 install
      apt: 
        name: "{{java_package}}"
        state: present