---
all:
  children:
    dotnetservers:
      hosts:
        localhost:
          dotnet_packages: 
            - dotnet-sdk-6.0
            - aspnetcore-runtime-6.0
            - dotnet-runtime-6.0
        172.31.24.105:
          packages_url: https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
          packages_dest: /tmp/packages-microsoft-prod.rpm
          dotnet_packages: 
            - dotnet-sdk-7.0
            - aspnetcore-runtime-7.0
            - dotnet-runtime-7.0