---
- name: Install Java-11
  hosts: all
  become: yes
  vars:
    java_package_ubuntu: default-jre
    java_package_centos: java-11-openjdk-devel
  tasks: 
    - name: apt update
      apt:
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: java-11 install
      apt: 
        name: "{{java_package_ubuntu}}"
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: java-11 install
      yum: 
        name: "{{java_package_centos}}"
        state: present
      when: ansible_facts['distribution'] == "CentOS"