---
- name: install nodejs on ubuntu
  hosts: all
  become: yes
  vars:
    nodejs_package_version: 18
    nodejs_package_url: "https://deb.nodesource.com/setup_{{nodejs_package_version}}.x"
    nodejs_package_dest: "/tmp/setup_{{nodejs_package_version}}.x.sh"
    nodejs_package: nodejs
  tasks: 
    - name: Downloading nodejs setup file
      ansible.builtin.get_url:
        url: "{{nodejs_package_url}}"
        dest: "{{nodejs_package_dest}}"
        mode: '0777'
    - name: Execute shell file
      ansible.builtin.shell: "{{nodejs_package_dest}}"
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
    - name: Install nodejs
      ansible.builtin.apt: 
        name: "{{nodejs_package}}"
        state: present