---
# handlers file for my
- name: start nginx
  ansible.builtin.systemd:
    name: "{{ nginx_packages }}"
    state: started
- name: restart nginx
  ansible.builtin.systemd:
    name: "{{ nginx_packages }}"
    state: restarted