---
- name: install nodejs on ubuntu and centos
  hosts: all
  become: yes
  vars:
    nodejs_package: nodejs
    nodejs_url: https://rpm.nodesource.com/setup_10.x
  tasks: 
    - name: install nodejs on centos
      ansible.builtin.shell: "curl –sL {{ nodejs_url }} | sudo bash -"
    - name: install nodejs 
      ansible.builtin.yum:
        name: "{{ nodejs_package }}"
        update_cache: yes
        state: present