---
- name: install nodejs on ubuntu and centos
  hosts: all
  become: yes
  vars:
    nodejs_package: 
      - nodejs
      - npm
  tasks: 
    - name: install nodejs on ubuntu
      ansible.builtin.apt:
        name: "{{ nodejs_package }}"
        update_cache: yes
        state: present