---
# vars file for my
microsoft_key_package_url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
dotnet_packages:
  - apt-transport-https
  - aspnetcore-runtime-7.0
nopCommerce_path: /var/www/nopCommerce
nopCommerce_url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.1/nopCommerce_4.60.1_NoSource_linux_x64.zip