---
- name: Install OpenMRS
  hosts: all
  become: yes
  tasks: 
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
    - name: install java
      ansible.builtin.apt:
        name: openjdk-8-jdk
        state: present
    - name: add tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: add tomcat user
      ansible.builtin.user:
        name: tomcat
        shell: /bin/false
        group: tomcat
        home: /opt/tomcat
    - name: download the tar file
      ansible.builtin.get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.tar.gz
        dest: /tmp/apache-tomcat-7.0.109.tar.gz
    - name: create the tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
    - name: tar the tomcat file
      ansible.builtin.unarchive: 
        src: /tmp/apache-tomcat-7.0.109.tar.gz
        dest: /opt/tomcat/
    - name: add a group the tomcat and recursive
      ansible.builtin.file:
        path: /opt/tomcat
        group: tomcat
        recurse: yes
    - name: give permissions to the conf
      ansible.builtin.file:
        path: /opt/tomcat/conf
        mode: '0750'
    - name: change the owner to the files
      ansible.builtin.file:
        path: 
          - /opt/tomcat/webapps/
          - /opt/tomcat/work/
          - /opt/tomcat/temp/
          - /opt/tomcat/logs/
        owner: tomcat
        recurse: yes
    - name: copy the tomcat.service file
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
    - name: daemon-reload & start tomcat
      ansible.builtin.systemd: 
        name: tomcat
        daemon_reload: yes
        state: started
    - name: create a OpenMRS directory
      ansible.builtin.file:
        path: /var/lib/OpenMRS
        state: directory
    - name: give ownership to OpenMRS
      ansible.builtin.file:
        path: /var/lib/OpenMRS
        owner: tomcat
        group: tomcat 
        recurse: yes
    - name: get file from url
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Platform_2.5.0/openmrs.war
        dest: /opt/tomcat/webapps/openmrs.war
    - name: change permissions of openmrs.war
      ansible.builtin.file:
        path: /opt/tomcat/webapps/openmrs.war
        owner: tomcat
        group: tomcat
        recurse: yes

