---
- name: Install tomcat
  hosts: all
  become: yes
  tasks: 
    - name: sudo apt update
      apt: 
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Install java-11
      package:
        name: "{{Java_package}}"
        state: present   